var __awaiter = (this && this.__awaiter) || function (thisArg, _arguments, P, generator) {
    function adopt(value) { return value instanceof P ? value : new P(function (resolve) { resolve(value); }); }
    return new (P || (P = Promise))(function (resolve, reject) {
        function fulfilled(value) { try { step(generator.next(value)); } catch (e) { reject(e); } }
        function rejected(value) { try { step(generator["throw"](value)); } catch (e) { reject(e); } }
        function step(result) { result.done ? resolve(result.value) : adopt(result.value).then(fulfilled, rejected); }
        step((generator = generator.apply(thisArg, _arguments || [])).next());
    });
};
import { routeHello, routeAPINames, routeWeather } from "./routes.js";
import express from "express";
import path from "path";
const server = express();
const port = 3000;
// Routes defined in the server
// The /hello route is a simple GET route that sends a response generated by the routeHello function.
server.get("/hello", function (_req, res) {
    const response = routeHello();
    res.send(response);
});
// The /api/names route is an asynchronous GET route. It uses the routeAPINames function to generate a response
server.get("/api/names", function (_req, res) {
    return __awaiter(this, void 0, void 0, function* () {
        let response;
        try {
            response = yield routeAPINames();
            res.send(response);
        }
        catch (err) {
            console.log(err);
        }
    });
});
//The /api/weather/:zipcode route is a GET route with a route parameter (:zipcode). The routeWeather function is used to generate a response.
server.get("/api/weather/:zipcode", function (req, res) {
    const response = routeWeather({ zipcode: req.params.zipcode });
    res.send(response);
});
server.get("/components/weather", function (req, res) {
    const filePath = path.join(process.cwd(), "public", "weather.html");
    res.setHeader("Content-Type", "text/html");
    res.sendFile(filePath);
});
server.listen(port, function () {
    console.log("Listening on " + port);
});
