import {routeHello, routeAPINames, routeWeather} from "./routes.js";
import express, {Request, Response} from "express";

import path from "path";

const server = express();
const port = 3000;

// Routes defined in the server
// The /hello route is a simple GET route that sends a response generated by the routeHello function.
server.get("/hello", function (_req: Request, res: Response): void {
    const response = routeHello();
    res.send(response);
});
// The /api/names route is an asynchronous GET route. It uses the routeAPINames function to generate a response
server.get("/api/names",
    async function (_req: Request, res: Response): Promise<void> {
        let response: string;
        try {
            response = await routeAPINames();
            res.send(response);
        } catch (err) {
            console.log(err);
        }
    }
);
//The /api/weather/:zipcode route is a GET route with a route parameter (:zipcode). The routeWeather function is used to generate a response.
server.get(
    "/api/weather/:zipcode",
    function (req: Request, res: Response): void {
        const response = routeWeather({zipcode: req.params.zipcode});
        res.send(response);
    }
);

server.get("/components/weather", function (req: Request, res: Response): void {
    const filePath = path.join(process.cwd(), "public", "weather.html");
    res.setHeader("Content-Type", "text/html");
    res.sendFile(filePath);
});

server.listen(port, function (): void {
    console.log("Listening on " + port);
});